version: '2'

services:
  eclipse-mosquitto:
    image: eclipse-mosquitto
    container_name: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 1884:1884
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf