AWS_ACCESS_KEY_ID=FAKE_AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=FAKE_AWS_SECRET_ACCESS_KEY
AWS_DEFAULT_REGION=FAKE_AWS_DEFAULT_REGION
AWS_SESSION_TOKEN=FAKE_AWS_SESSION_TOKEN

docker run --rm \
  -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} \
  -e AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} \
  amazon/aws-cli \
  s3 ls
