version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq
    networks:
      - net
    ports:
      - 15672:15672
      - 5672:5672
networks:
  net:
